theme = "tale2"
title = "Backyard"
googleAnalytics = ""
disqusShortname = ""
enableEmoji = "true"

[Author]
  name = "Basil"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/post"
    weight = 1
  [[menu.main]]
  identifier = "watchlog"
  name = "Watchlog"
  title = "Watchlog"
  url = "/watchlog/"
  weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 3

[Params]
  css = ["css/custom.css"]